openapi: 3.0.0
info:
  title: Laundry POS API
  description: API untuk layanan POS Laundry
  version: 1.0.0
servers:
  - url: https://laundry-pos-ten.vercel.app
paths:
  /register:
    post:
      summary: Registrasi pengguna baru
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        "201":
          description: Pengguna berhasil didaftarkan

  /login:
    post:
      summary: Login pengguna
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login berhasil

  /customers:
    post:
      summary: Tambah pelanggan
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                phoneNumber:
                  type: string
      responses:
        "201":
          description: Pelanggan berhasil ditambahkan
    get:
      summary: Dapatkan semua pelanggan
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Daftar pelanggan

  /customer-id:
    get:
      summary: Dapatkan pelanggan berdasarkan ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detail pelanggan
    put:
      summary: Perbarui pelanggan
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                fullName:
                  type: string
                email:
                  type: string
                phoneNumber:
                  type: string
      responses:
        "200":
          description: Pelanggan berhasil diperbarui
    delete:
      summary: Hapus pelanggan
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Pelanggan berhasil dihapus

  /services:
    get:
      summary: Dapatkan semua layanan
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Daftar layanan
    post:
      summary: Tambah layanan
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                serviceName:
                  type: string
                description:
                  type: string
                unitPrice:
                  type: integer
                unit:
                  type: string
      responses:
        "201":
          description: Layanan berhasil ditambahkan

  /service-id:
    get:
      summary: Dapatkan layanan berdasarkan ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detail layanan
    put:
      summary: Perbarui layanan
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                serviceName:
                  type: string
                description:
                  type: string
                unitPrice:
                  type: integer
                unit:
                  type: string
      responses:
        "200":
          description: Layanan berhasil diperbarui
    delete:
      summary: Hapus layanan
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Layanan berhasil dihapus

  /create-payment:
    post:
      summary: Buat pembayaran
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                transactionId:
                  type: string
      responses:
        "201":
          description: Pembayaran berhasil dibuat

  /payments:
    get:
      summary: Dapatkan semua pembayaran
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Daftar pembayaran

  /payment-detail:
    get:
      summary: Dapatkan pembayaran berdasarkan ID
      security:
        - bearerAuth: []
      parameters:
        - name: order_id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detail pembayaran

  /transactions:
    get:
      summary: Dapatkan semua transaksi
      security:
        - bearerAuth: []
      responses:
        "200":
          description: Daftar transaksi
    post:
      summary: Tambah transaksi
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      serviceId:
                        type: string
                      quantity:
                        type: integer
                paymentMethod:
                  type: string
      responses:
        "201":
          description: Transaksi berhasil ditambahkan

  /transaction-id:
    get:
      summary: Dapatkan transaksi berdasarkan ID
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Detail transaksi
    put:
      summary: Perbarui transaksi
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                customerId:
                  type: string
                items:
                  type: array
                  items:
                    type: object
                    properties:
                      serviceId:
                        type: string
                      quantity:
                        type: integer
                paymentMethod:
                  type: string
      responses:
        "200":
          description: Transaksi berhasil diperbarui
    delete:
      summary: Hapus transaksi
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Transaksi berhasil dihapus

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
